sudo: requiered
services:
  - docker
  
before_install:
  - docker build -t patilume/docker-react1 -f Dockerfile.dev . 
  
script:
  - docker run patilume/docker-react1 npm run test -- --coverage

deploy:
  provoider: elastickbenstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-341625096735"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY